myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp" #is used to create namespace

urlpatterns = [
    path('',views.index,name='index'),
    path('home',views.home,name='home'),
    path('fact/<n>',views.fact,name='fact'),
    path('child/',views.child,name='child'),
]

p4/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include("myapp.urls")),
    path('sam/',views.sam,name='sam'),
    
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from math import factorial
# Create your views here.
def index(request):
    return HttpResponse("<h1>welcome to myapp page</h1>")
def home(request):
    return render(request,"myapp/home.html",{'name':"reyaz"})
def fact(request,n):
    n=int(n)
    return HttpResponse("<h2>factorial is {}</h2>".format(factorial(n)))
def child(request):
    return render(request,"child.html")
def sam(request):
    return render(request,"myapp/sam.html")     

templates/child.html
  {% extends "myapp/base.html" %}

    {% block title %}
    <title>child html file</title>
    {% endblock %}
    <!--{% block body_block %}
    <body>
    <h2>welcome to child.html</h2>
    </body>
    {% endblock %}-->
    {% block content %}
    <h1>welcome to child .html</h1>
    <a href="{% url 'myapp:child' %}">home</a>

    {% endblock %}

templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
       
    <title>base html file</title>
{% endblock %}


</head>
<!--{% block body_block %}
<body>
    <h1>welcome to base.html</h1>
</body>
{% endblock %}-->
<body>
    <h1>navbar</h1>
{% block content %}
<h1>welcome to base.html</h1>
{% endblock %}
</body>
</html>

templates/myapp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>welcome to home pags</h1>
</body>
</html>

templates/myapp/sam.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h1>welcome to sam.html</h1>
<a href="{% url 'myapp:child' %}">child</a>
<a href="{% url 'myapp:home' %}">home</a>    
</body>
</html>